name: 'flight_analytics'
version: '1.0.0'
config-version: 2

profile: 'flight_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  flight_analytics:
    bronze:
      +materialized: view
      +schema: bronze
      +tags: ['bronze']
    silver:
      +materialized: table
      +schema: silver
      +tags: ['silver']
    gold:
      +materialized: table
      +schema: gold
      +tags: ['gold']

vars:
  'dbt_date:time_zone': 'UTC'