{{
  config(
    materialized='table',
    tags=['gold', 'anomalies'],
    partition_by={
      "field": "WINDOW_START",
      "data_type": "timestamp",
      "granularity": "hour"
    },
    cluster_by=['WINDOW_START', 'IS_ANOMALY', 'ORIGIN_COUNTRY']
  )
}}

-- Flag flights with velocity beyond 2 standard deviations
WITH flight_stats AS (
  SELECT
    ICAO24,
    ORIGIN_COUNTRY,
    TIME_POSITION,
    VELOCITY_VALIDATED,
    DATE_TRUNC('HOUR', TIME_POSITION) AS WINDOW_START,
    AVG(VELOCITY_VALIDATED) OVER (PARTITION BY DATE_TRUNC('HOUR', TIME_POSITION)) AS HOURLY_MEAN_VELOCITY,
    STDDEV(VELOCITY_VALIDATED) OVER (PARTITION BY DATE_TRUNC('HOUR', TIME_POSITION)) AS HOURLY_STDDEV_VELOCITY
  FROM {{ ref('silver_flights_cleaned') }}
  WHERE TIME_POSITION IS NOT NULL
    AND VELOCITY_VALIDATED IS NOT NULL
)

SELECT
  WINDOW_START,
  ICAO24,
  ORIGIN_COUNTRY,
  TIME_POSITION,
  VELOCITY_VALIDATED,
  HOURLY_MEAN_VELOCITY,
  HOURLY_STDDEV_VELOCITY,
  ABS(VELOCITY_VALIDATED - HOURLY_MEAN_VELOCITY) / NULLIF(HOURLY_STDDEV_VELOCITY, 0) AS Z_SCORE,
  CASE
    WHEN ABS(VELOCITY_VALIDATED - HOURLY_MEAN_VELOCITY) > 2 * HOURLY_STDDEV_VELOCITY THEN TRUE
    ELSE FALSE
  END AS IS_ANOMALY,
  CURRENT_TIMESTAMP() AS LOAD_TIME
FROM flight_stats
