{{
  config(
    materialized='table',
    tags=['gold', 'aircraft_detail']
  )
}}

-- Active aircraft tracking
SELECT
  ICAO24,
  ORIGIN_COUNTRY,
  MIN(TIME_POSITION) AS FIRST_SEEN,
  MAX(TIME_POSITION) AS LAST_SEEN,
  COUNT(*) AS POSITION_COUNT,
  AVG(VELOCITY_VALIDATED) AS AVG_VELOCITY,
  MAX(VELOCITY_VALIDATED) AS MAX_VELOCITY,
  AVG(BARO_ALTITUDE) AS AVG_ALTITUDE,
  SUM(CASE WHEN ON_GROUND = TRUE THEN 1 ELSE 0 END) AS GROUND_TIME_SAMPLES,
  SUM(CASE WHEN ON_GROUND = FALSE THEN 1 ELSE 0 END) AS AIRBORNE_TIME_SAMPLES,
  CURRENT_TIMESTAMP() AS LOAD_TIME
FROM {{ ref('silver_flights_cleaned') }}
WHERE TIME_POSITION IS NOT NULL
GROUP BY 1, 2