-- Silver model: Cleaned and normalized flight data
WITH bronze AS (
    SELECT *
    FROM {{ ref('stg_flights_bronze') }}
)
SELECT
    WINDOW_START,
    TRIM(ICAO24) AS ICAO24,
    TRIM(ORIGIN_COUNTRY) AS ORIGIN_COUNTRY,
    TRY_CAST(LATITUDE AS FLOAT) AS LATITUDE,
    TRY_CAST(LONGITUDE AS FLOAT) AS LONGITUDE,
    TRY_CAST(TIME_POSITION AS NUMBER) AS TIME_POSITION,
    TRY_CAST(LAST_CONTACT AS NUMBER) AS LAST_CONTACT,
    TRY_CAST(VELOCITY AS FLOAT) AS VELOCITY,
    TRY_CAST(VERTICAL_RATE AS FLOAT) AS VERTICAL_RATE,
    TRY_CAST(TRUE_TRACK AS FLOAT) AS TRUE_TRACK,
    TRY_CAST(BARO_ALTITUDE AS FLOAT) AS BARO_ALTITUDE,
    TRY_CAST(ON_GROUND AS BOOLEAN) AS ON_GROUND
FROM bronze
WHERE ICAO24 IS NOT NULL
